okta:
  oauth2:
    issuer: https://dev-536052.okta.com/oauth2/default
    client-id: 0oafsibz8WCID2ibc4x6
    client-secret: ThFQdMb0ax8V9ZF2LDmkBZuN72JmB09TWircQXNO
app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/postgresdb
    username: postgres
    password: password
